name:  publish nuget package

on:  
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: run minver
      id: version
      uses: thefringeninja/action-minver@2.0.0-preview1
    - name: output
      run: |
        echo ${{ steps.version.outputs.version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish to NuGet
      id: publish_nuget
      uses: alirezanet/publish-nuget@v3.0.2
      with:
        PROJECT_FILE_PATH: src/Octopus.Config.Exporter.Cli.fsproj
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_KEY}}
        VERSION_STATIC: ${{ steps.version.outputs.version }}
        INCLUDE_SYMBOLS: true

